<script setup>
import {computed,ref,nextTick} from 'vue'
import {db,ui} from './store'
import {organizationPath} from './organization'
import ReviewDrawer from './ReviewDrawer.vue'
const selected=ref('school:md-primary'),studentId=ref(300),reviewId=ref(null)
const tree=computed(()=>db.schools.map(s=>({title:s.name,key:'school:'+s.id,children:db.grades.filter(g=>g.schoolId===s.id).map(g=>({title:'年级：'+g.name,key:'grade:'+g.id,children:db.classes.filter(c=>c.gradeId===g.id).map(c=>({title:'班级：'+c.name,key:'class:'+c.id,children:db.students.filter(x=>x.classId===c.id).map(x=>({title:`${x.name} · 班号 ${x.number}`,key:'student:'+x.id}))}))}))})))
const members=computed(()=>{const [kind,id]=selected.value.split(':');return db.students.filter(s=>kind==='student'?String(s.id)===id:s[kind+'Id']===id)})
const student=computed(()=>db.students.find(s=>s.id===studentId.value))
const compositions=computed(()=>db.submissions.filter(r=>r.studentId===studentId.value).map(r=>({...r,task:db.tasks.find(t=>t.id===r.taskId)})))
function select(keys){if(!keys.length)return;selected.value=keys[0];if(members.value.length&&!members.value.some(s=>s.id===studentId.value))studentId.value=members.value[0].id}
function openApp(r){ui.studentId=r.studentId;ui.taskId=r.taskId;ui.appPage='任务';ui.tab='app';nextTick(()=>{ui.appDetail=true})}
</script>
<template><div class="organization-layout"><div class="panel"><h2>学校与教学组织</h2><p class="drawer-copy">2026—2027 学年</p><a-tree :tree-data="tree" :default-expanded-keys="['school:md-primary','grade:p3','class:p3a']" :selected-keys="[selected]" @select="select"/></div><div><div class="panel"><div class="panel-head"><h2>学生名单</h2><a-tag>{{members.length}} 人</a-tag></div><a-table :data-source="members" row-key="id" :pagination="{pageSize:5}" :columns="[{title:'姓名',dataIndex:'name'},{title:'学校 / 年级 / 班级',key:'path'},{title:'班号',dataIndex:'number'},{title:'操作',key:'action'}]"><template #bodyCell="{column,record}"><template v-if="column.key==='path'">{{organizationPath(db,record)}}</template><a-button v-if="column.key==='action'" type="link" @click="studentId=record.id">查看作文</a-button></template></a-table></div><div class="panel" v-if="student"><div class="panel-head"><div><h2>{{student.name}}的作文档案</h2><p>{{organizationPath(db,student)}} · 班号 {{student.number}} · 学生 ID {{student.id}}</p></div><a-tag color="blue">{{compositions.length}} 篇任务记录</a-tag></div><p class="muted" style="margin-bottom:16px">每篇作文对应独立任务，分别保存原稿、评分方案及已发布反馈。</p><a-table :data-source="compositions" row-key="id" :pagination="false" :columns="[{title:'作文题目',key:'title'},{title:'截止日期',key:'due'},{title:'状态',dataIndex:'status'},{title:'成绩',key:'score'},{title:'操作',key:'action'}]"><template #bodyCell="{column,record}"><template v-if="column.key==='title'">{{record.task.title}}</template><template v-if="column.key==='due'">{{record.task.due}}</template><template v-if="column.key==='score'">{{record.published?record.published.total+' / '+record.published.max:'—'}}</template><template v-if="column.key==='action'"><a-button type="link" size="small" @click="openApp(record)">学生端查看</a-button><a-button v-if="ui.role==='任课教师'&&['待复核','已复核','已发布'].includes(record.status)" type="link" size="small" @click="reviewId=record.id">查看 / 复核</a-button></template></template></a-table></div></div></div><ReviewDrawer v-if="reviewId" :id="reviewId" @close="reviewId=null"/></template>
